レスポンシブ&ハンバーガーメニュー実装
gudetanuki/Company-HomePage pull request #14
Opened 2022-04-12 14:37 UTC by gudetanuki

サイト４ページのレスポンシブ実装と、
ヘッダー部分のハンバーガーメニューを実装しました。
確認をお願いします。

2022-04-16 02:00 UTC, Atsuage-P requested changes

2022-04-16 02:00 UTC, Atsuage-P commented on src/js/accordion.js
> +// 'use strict';
コメントにしなくていいんじゃないかな

2022-04-16 02:00 UTC, Atsuage-P commented on src/js/accordion.js
> +    });
問合せと答えの量が少ないからforeachでループ回すのいいけど量が多くなってきたら重くなったりするから、htmlの`onclick`を調べて使ってみるといいかも

2022-04-16 02:00 UTC, Atsuage-P commented on src/js/main2.js
> +toggleHamburgerMenu();
`main.js`と内容ほぼ同じだからこれ削除して`main.js`を全ページで読み込むようにしようか

2022-04-16 02:00 UTC, Atsuage-P commented on src/js/observer.js
> +// 'use strict';
コメント解除

2022-04-16 02:00 UTC, Atsuage-P commented on src/scss/company.scss
>  @import "observer.scss";
ファイルをディレクトリにまとめる
設定用ディレクトリ、コンポーネント用ディレクトリとか
`@import setting/*.scss`ってやったらディレクトリの中身全部読むのでたくさんimport書かなくていい

2022-04-16 14:55 UTC, Atsuage-P approved these changes
余計な改行とかコメントとか削除してmergeする
その後、別ブランチ切ってhtmlの共通部分をテンプレートエンジンで共通化させる

2022-04-16 14:55 UTC, Atsuage-P commented on src/js/accordion.js
> +};
イベントハンドラを使う方法もあるらしい
https://www.zunouissiki.com/diffrent-target-currenttarget/
やらなくていいけど見てみてね

2022-04-16 14:55 UTC, Atsuage-P commented on src/scss/company.scss
> +// @import "observer.scss";
消す
他のも全部

2022-04-18 11:52 UTC, gudetanuki commented on src/js/accordion.js
> +};
ミマシタ

2022-04-18 13:50 UTC, merged