TOPページコーディング完成
gudetanuki/Company-HomePage pull request #3
Opened 2022-04-04 12:59 UTC by gudetanuki

TOPページのHTML&CSSコーディングが一通り完成したので、確認をお願いします。

2022-04-05 13:38 UTC, Atsuage-P requested changes
`style.scss`は本当は@importだけの方がいい
汎用的なパーツをファイル別で作ってそのパーツの寄せ集めでページを作る

2022-04-05 13:38 UTC, Atsuage-P commented on dist/index.html
> +            </p>
文章の段落ではないのでdivとかかな

2022-04-05 13:38 UTC, Atsuage-P commented on dist/index.html
> +      <p>お気軽にお問い合わせください！</p>
ここも段落ではない

2022-04-05 13:38 UTC, Atsuage-P commented on dist/index.html
> +          <dt>00.00.00</dt>
何の数字？

2022-04-05 13:38 UTC, Atsuage-P commented on dist/index.html
> +            <p>00-0000-0000</p>
段落ではない

2022-04-05 13:38 UTC, Atsuage-P commented on dist/index.html
> +        <p class="copylight">©️ 2022 mission</p>
段落ではない

2022-04-05 13:38 UTC, Atsuage-P commented on src/scss/_base.scss
> +  }
使い方特殊だから`_utility.scss`でもいいのでは

2022-04-05 13:38 UTC, Atsuage-P commented on src/scss/_footer.scss
> +  height: 450px;
`height`指定いるのかな

2022-04-05 13:38 UTC, Atsuage-P commented on src/scss/_footer.scss
> +      a {
これとか使いまわせるようにclassにしたらいいんじゃないかな

2022-04-05 13:38 UTC, Atsuage-P commented on src/scss/_footer.scss
> +    height: 70px;
これとか下と重複してるので、アイコンサイズだけのclass作ってそれぞれに当てる方が綺麗そう

2022-04-05 13:38 UTC, Atsuage-P commented on src/scss/_utility.scss
> +    transition: all .5s;
下と内容が重複、継承を使うとまとまる
`@extend`

2022-04-05 13:38 UTC, Atsuage-P commented on src/scss/_utility.scss
> +  transition: all .5s;
ここも`transition`, `border`, `background-color`とか重複してるのでベースを作って継承使う

2022-04-05 13:38 UTC, Atsuage-P commented on src/scss/reset.scss
> +/*! destyle.css v3.0.2 | MIT License | https://github.com/nicolas-cusan/destyle.css */
ファイル名`_`いるのでは

2022-04-05 13:38 UTC, Atsuage-P commented on src/scss/_mixin.scss
> +}
これだけだとmixinにする意味ない

2022-04-05 13:38 UTC, Atsuage-P commented on src/scss/_mixin.scss
> +@mixin font-size {
これいる？

2022-04-05 13:38 UTC, Atsuage-P commented on src/scss/style.scss
> +.contact {
これとか他でも使い回すはず
別ファイルに切り出す

2022-04-05 13:38 UTC, Atsuage-P commented on dist/index.html
> +            <div class="icon icon-facebook"></div>
本来リンクでは？

2022-04-06 01:36 UTC, gudetanuki commented on dist/index.html
> +          <dt>00.00.00</dt>
日付のつもりです。

2022-04-06 01:54 UTC, gudetanuki commented on src/scss/_footer.scss
> +  height: 450px;
いらなそうだったので
width,heightともに消しました。

2022-04-06 02:56 UTC, gudetanuki commented
google iconをheadタグではなくnpmでの読み込みに変更できていませんが一旦プッシュします。

2022-04-06 23:52 UTC, Atsuage-P requested changes

2022-04-06 23:52 UTC, Atsuage-P commented on src/scss/_utility.scss
> +.button-base {
`button-base`自体はclassとして使わないのであれば、プレースホルダーセレクタにする
https://seisaku.fun/web/sass-extend/#toc-1

2022-04-06 23:52 UTC, Atsuage-P commented on src/scss/style.scss
> +      cursor: pointer;
dtとdlで被ってる部分は
`dt, dl {}`で指定して個別の部分は個別にしたほうが見やすそう

2022-04-06 23:52 UTC, Atsuage-P commented on dist/index.html
> +            <a href="#" class="icon icon-size icon-insta"></a>
`icon-size`ってclassある？

2022-04-06 23:52 UTC, Atsuage-P commented on src/scss/_header.scss
> +  color: $font-color-white;
`_base.scss`の`a`と重複

2022-04-06 23:52 UTC, Atsuage-P commented on src/scss/_utility.scss
> +span {
`span`全部これ適用されるけどclassにしなくていいの？

2022-04-07 13:10 UTC, gudetanuki commented on dist/index.html
> +            <a href="#" class="icon icon-size icon-insta"></a>
utility.scssにあります。

2022-04-07 13:11 UTC, gudetanuki commented on src/scss/_utility.scss
> +span {
classつけました。

2022-04-09 05:30 UTC, Atsuage-P approved these changes
修正したらmergeしてください

2022-04-09 05:30 UTC, Atsuage-P commented on src/scss/_button.scss
> +.button-small {
`&-small`

2022-04-09 05:30 UTC, Atsuage-P commented on src/scss/_utility.scss
> +.memu-list {
`&-list`

2022-04-09 05:30 UTC, Atsuage-P commented on src/scss/_utility.scss
> +.menu-link {
`&-link`

2022-04-09 05:30 UTC, Atsuage-P commented on src/scss/_utility.scss
> +.memu-list {
`_foooter.scss`の`menu-list`と名前が重複してるので事故りそう

2022-04-09 05:30 UTC, Atsuage-P commented on dist/index.html
> +            <dt>00.00.00</dt>
0並べるより適当な日付入れた方がいいかも

2022-04-09 06:04 UTC, merged